name: needs
on:
  push:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo im done
          exit 1

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo do not exec this job
