name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "set repo prefix"
        required: true
        default: "service"
        type: choice
        options:
          - example
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN}} | gh auth login --with-token
      - name: create-repo
        id: create-repo
        run: |
          gh repo create lsh-github-action/${{inputs.prefix}}-${{inputs.name}} --public --add-readme
      - uses: actions/checkout@v2
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "repo auto creation"
          SLACK_TITLE: "${{steps.create-repo.outcome}}"
          SLACK_USERNAME: codefug
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
