name: output
on: push

jobs:
  create_output:
    runs-on: ubuntu-latest
    steps:
      - name: echo output
        id: check-output
        run: |
          echo "test=hello" >> "$GITHUB_OUTPUT"
      - name: echo output
        id: check-output-2
        run: |
          echo "test=hello2" >> "$GITHUB_OUTPUT"
      - name: check output
        run: |
          echo ${{steps.check-output.outputs.test}}
          echo ${{steps.check-output-2.outputs.test}}
