name: contexts
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: JSON으로 context변환
        run: echo '${{ toJSON(github) }}'

  checkoutcontext:
    runs-on: ubuntu-latest
    needs: [context]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: JSON으로 context변환
        run: echo '${{ toJSON(github)}}'
