name: issueAlert
on:
  issues:
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get keyword
        id: get-keyword
        run: |
          echo level=Undefined >> $GITHUB_OUTPUT
          keywords=$(cat keyword.txt)
          for keyword in $keywords; do
            if [[ "${{github.event.issue.title }}" =~ "$keyword" ]]; then
              echo level=$keyword >> $GITHUB_OUTPUT
            fi
          done
      - name: get output
        run: |
          echo ${{ steps.get-keyword.outputs.level}}
  slack:
    needs: [get-keyword]
    if: needs.get-keyword.outputs.level != 'Undefined'
    runs-on: ubuntu-latest
    environment: ${{needs.get-keyword.outputs.level}}
    name: Slack Notification
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "cancelled"
          SLACK_TITLE: "good"
          SLACK_MESSAGE: "${{github.event.issue.html_url}}"
