name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: "first inputs"
        required: true
        default: "github-actions"
        type: string
      environment:
        description: "second inputs"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo git action
      - name: echo inputs
        run: |
          echo ${{inputs.name}}
          echo ${{inputs.environment}}
